name: Deploy Index and Assets

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Copy the specific files and the entire asset folder
      - name: Isolate Files
        run: |
          mkdir public-dist
          cp index.html public-dist/
          cp script.js public-dist/
          cp style.css public-dist/

      - name: Upload Page Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public-dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
